version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php
      - postgres

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    command: >
      sh -c "chown -R www-data:www-data /var/www/laravel/storage /var/www/laravel/bootstrap/cache && chmod -R 775 /var/www/laravel/storage /var/www/laravel/bootstrap/cache && php-fpm"

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: [ "php","/var/www/laravel/artisan" ]

volumes:
  postgres_data: